version: '3.6'

services:
  nginx-server:
    build: 
      dockerfile: Dockerfile
      context: .
    network_mode: host
    volumes:
      - type: bind
        source: ./conf/nginx.conf
        target: /usr/local/nginx/conf/nginx.conf
